### ISSUE TITLE
Background videos not displaying

### ISSUE THREAD

**Issue by NoahLutz** [declantyson/doto#10] opened 2017-10-02 04:38 UTC
When I restart lightdm with the doto theme, I am brought to a black screen with just the time and password input. When I type in my password and hit enter, nothing seems to happen.

I am running on Arch and bspwm.

**Comment by declantyson** [comment] 2017-10-02 08:50
Hi @NoahLutz 

Can you please post the contents of your greeter.log file?

**Comment by NoahLutz** [comment] 2017-10-02 13:24
Here is the greeter.log file contents.
```

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=bbc-sport&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=bbc-sport&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=bbc-sport&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=bbc-news&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=bbc-news&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=ars-technica&sortBy=top due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://api.openweathermap.org/data/2.5/weather?appid=c3ec0e268239d674fbe215f89868ee73&units=metric&q=London,GB due to access control checks.

** (WebKitWebProcess:7363): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=e0fddafbeb304299913237a89228f313&source=bbc-sport&sortBy=top due to access control checks.
```

It looked like all the errors were coming from widget.js so I commented out the newsfeed and weather calls in start.js and tried to run it again but got the same result with different errors. Here is the greeter.log with newsfeed and weather widgets commented out.
```

** (WebKitWebProcess:11478): CRITICAL **: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
Gdk-Message: lightdm-webkit2-greeter: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

Gdk-Message: WebKitWebProcess: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

**Comment by declantyson** [comment] 2017-10-02 15:56
ok it looks like the first error you're experiencing is a duplicate of #8.

As for the second error it looks like it's a problem with webkit2gtk. What version of webkit2gtk are you running? https://github.com/Antergos/web-greeter/issues/107

**Comment by NoahLutz** [comment] 2017-10-02 16:50
I am running webkit2gtk-2.16.6-1. I tried downgrading to webkit2gtk-2.14.2-2 like suggested in the issue you linked, but that stopped lightdm from running at all

**Comment by skrambol** [comment] 2017-10-07 10:31
Hi @NoahLutz kindly check my comment in #8 to solve this.

As for the password, it was working for me before, then I change something somewhere in some config and the password authentication worked. Now, I reinstalled lightdm and lightdm-webkit2-greeter to check if this problem persists and it does.

I'm trying to retrace my steps in order to make it work since I forgot to backup my config files before reinstalling.

EDIT:

A quick and simple fix for the background, you can change the `assets/images/black.jpg` to your preferred background image.

UPDATE:

In your `/etc/lightdm/lightdm.conf` set the following
```conf
[Seat:*]
# under this setting or its equivalent
# change the user-session to your preferred session
# for example:
user-session=bspwm
```
This should let you log-in successfully. Tell me how it goes.

**Comment by NoahLutz** [comment] 2017-10-11 14:32
@systemplado That seems to work! I can now log in! 

As you said in #8, `mp4`'s still don't load and I checked the `seat0-greeter.log` file and it still has this error.
```
** (WebKitWebProcess:11595): CRITICAL **: lightdm_greeter_respond: assertion 'priv->n_responses_waiting > 0' failed
```

Not sure if this is related at all

**Comment by declantyson** [comment] 2017-10-13 20:43
@systemplado here's the contents of my `lightdm-webkit-greeter.conf`

```
[greeter]
webkit-theme=default
font-name=Ubuntu 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
```

It's basically the defaults (xft is for font handling only) - only other thing I can see is that I have doto installed in the default folder.

Seems stupid, but what's your permissions on the assets folder? Mine is set to 775.

**Comment by skrambol** [comment] 2017-10-14 02:37
@declantyson I've followed your config and still ended up not loading the background video.

Even the console/debugger did not load properly the file:
![screenshot](https://i.imgur.com/MCyOi1Z.png)

**Comment by declantyson** [comment] 2017-10-14 10:48
@systemplado How did you get the console to appear? I can't get it to appear with any of the normal shortcuts. Starting to think we're on different versions of something somewhere that's causing problems...

**Comment by skrambol** [comment] 2017-10-14 11:09
I set the `debug_mode` to `true` in my `lightdm-webkit2-greeter.conf` then while the greeter is running, either through log-in or by typing `lightdm-webkit2-greeter` in your terminal, right click then inspect element.

**Comment by declantyson** [comment] 2017-10-14 11:29
That's really quite unusual - I don't have an inspect element item in my menu

**Comment by NoahLutz** [comment] 2017-10-17 04:04
Its interesting, I can enable debug mode and see the debug console, but when I go into the resources tab, like @systemplado, I see no `mp4` being loaded. Theres not even the `Other` folder like in the picture.

Another interesting thing I noticed is that I can open `index.html` in a browser and the background video will load just fine. 

It's seems to me like the issue is with webkit2gtk? what versions of webkit2gtk are you both running?

**Comment by skrambol** [comment] 2017-10-17 10:14
I'm currently using version `2.2.5` which is the same from the [AUR](https://aur.archlinux.org/packages/lightdm-webkit2-greeter/). I'll try installing it on an Ubuntu machine (or VM) as soon as I get my hands on one.

EDIT:
My lightdm version is `1.22.0` which is given by `lightdm -v`
webkit2gtk is version `2.16.6-1` I'm currently updating it to the current which is `2.18.0-1` and see if the background video will load.

EDIT2:
Nothing happened when I updated to `2.18.0-1`. Also, @NoahLutz in order to have the `Other` folder, try reloading the greeter via `Right Click > Reload`

**Comment by declantyson** [comment] 2017-10-17 20:50
@NoahLutz @systemplado 

lightdm version: `1.18.3`
lightdm-webkit-greeter version: `0.1.2-0ubuntu3`
webkit2gtk version: `2.4.11-0ubuntu0.1`

So, I'm actually behind you guys on all of these things.

**Comment by NoahLutz** [comment] 2017-10-18 21:06
Hmm. It seems like both @systemplado and I are using lightdm-webkit2-greeter rather than lightdm-webkit-greeter. Maybe this is the issue? i tried installing lightdm-webkit-greeter from the [AUR](https://aur.archlinux.org/packages/lightdm-webkit-greeter/) but after 4 + hrs of waiting for it to compile I gave up.

**Comment by declantyson** [comment] 2017-10-23 21:02
Well in the process of trying to confirm this I've managed to somehow mess up lightdm on my machine entirely... will have to park this one for a bit :slightly_frowning_face:

**Comment by joaquingx** [comment] 2018-01-18 09:15
Exactly the same problem here :cry:

**Comment by ghost** [comment] 2018-05-20 12:24
Same issue. Any workaround on this problem? :(

**Comment by ghost** [comment] 2018-05-21 22:36
Fixed the problem by installing webkitgtk. Hours of compiling is worth it. :smile:  https://prnt.sc/jkvs9q

**Comment by skrambol** [comment] 2018-05-22 01:16
@undefinedhax great find! What is your current set-up (OS, etc.)? Can you also provide a link for webkitgtk?

**Comment by ghost** [comment] 2018-05-22 13:22
@systemplado Arch Linux is my OS. BSPWM as my wm. I used the webkitgtk in AUR. Also, you can use the repo archlinuxcn. It has a pre-compiled webkitgtk for less hassle in compiling. Sorry for my bad english...not my native language hehe :grin:

**Comment by declantyson** [comment] 2018-05-23 07:04
@undefinedhax Thanks! I will mark this as closed now.

**Comment by joaquingx** [comment] 2018-05-24 01:41
Hello,

I'm installed webkitgtk but the problem persists. I think this is because my lighdtm-webkit2-greeter.conf, someone with the greeter working can share his .conf file? My .conf is:

```
#
# [greeter]
# debug_mode          = Greeter theme debug mode.
# detect_theme_errors = Provide an option to load a fallback theme when theme errors are detected.
# screensaver_timeout = Blank the screen after this many seconds of inactivity.
# secure_mode         = Don't allow themes to make remote http requests.
# time_format         = A moment.js format string so the greeter can generate localized time for display.
# time_language       = Language to use when displaying the time or "auto" to use the system's language.
# webkit_theme        = Webkit theme to use.
#
# NOTE: See moment.js documentation for format string options: http://momentjs.com/docs/#/displaying/format/
#

[greeter]
debug_mode          = false
detect_theme_errors = true
screensaver_timeout = 300
secure_mode         = false
time_format         = LT
time_language       = auto
webkit_theme        = doto

#
# [branding]
# background_images = Path to directory that contains background images for use by themes.
# logo              = Path to logo image for use by greeter themes.
# user_image        = Default user image/avatar. This is used by themes for users that have no .face image.
#
# NOTE: Paths must be accessible to the lightdm system user account (so they cannot be anywhere in /home)
#

[branding]
background_images = /usr/share/lightdm-webkit/themes/doto
logo              = /usr/share/pixmaps/archlinux-logo.svg
user_image        = /usr/share/pixmaps/archlinux-user.svg
```

**Comment by declantyson** [comment] 2018-06-20 21:14
Hey @joaquingx 

Your config looks fine.

I've just done a fresh install and found that you may need the following additional packages that aren't necessarily automatically installed with webkitgtk:

- gstreamer1.0-libav
- gstreamer1.0-plugins-bad-videoparsers

This is for Ubuntu 16.04 but could apply to you too.

**Closed as completed** 2018-09-10 10:41 UTC
Labels: bug, Hacktoberfest
